# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

ARG BASE_IMAGE=greengrass-base:local
FROM ${BASE_IMAGE}

# Install Greengrass v2 dependencies
RUN yum update -y && \
    yum install -y python3-pip

RUN python3 -m pip install --no-cache-dir awsiotsdk

LABEL org.opencontainers.image.description="Greengrass release image (extends Dockerfile base)"
